#!/bin/bash
export PIPEVER=0.8.0.F

##################
# BASE FUNCTIONS #
##################

CORES=${SLURM_CPUS_PER_TASK:-${SLURM_JOB_CPUS_PER_NODE%%\(*} }; CORES=${CORES//[[:space:]]/}; CORES=${CORES:-$(nproc 2>/dev/null || echo 1)}
export SCRIPTS=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

export BASE_DIR="/project/colletotrichum_ga_625"
export PROJECT_DIR="$BASE_DIR/COLLETOTRICHUM"

###############################
# CORE FUNCTIONAL DIRECTORIES #
###############################

export SOFTWARE="$BASE_DIR/software"
export ENVS="$BASE_DIR/envs"
export DBS="$BASE_DIR/Databases"

##################################
# PROJECT DEPENDENCY DIRECTORIES #
##################################

export RAW="$PROJECT_DIR/RawSequences"
export REFS="$PROJECT_DIR/References"
export ASSEMBLY="$PROJECT_DIR/Assembly"
export ANNOTATION="$PROJECT_DIR/Annotation"
export PAN="$PROJECT_DIR/Pangenome"

###########################
# ASSEMBLY SUBDIRECTORIES #
###########################

export TRIMS="$ASSEMBLY/ExportedTrims"
export KRAKEN="$ASSEMBLY/Kraken"
export SPADES="$ASSEMBLY/Spades"
export QUAST="$ASSEMBLY/Quast"
export BUSCO="$ASSEMBLY/BUSCO"
export BUSCODL="$DBS/BuscoDL"
export PILON="$ASSEMBLY/Pilon"
export ASSEMBLIES="$ASSEMBLY/Assemblies"
export READS="$ASSEMBLY/Reads"
export HIFI="$ASSEMBLY/HiFiASM"
export FASTA="$ASSEMBLY/FASTA"
export SEQK="$ASSEMBLY/SeqKit"
export TIDK="$ASSEMBLY/TIDK"
export FUN2CLEAN="$ASSEMBLY/Cleaned"

#################################
# OPTIONAL CONTAMINANT CLEANING #
#################################

export BAM="$ASSEMBLY/BamMaker"
export BLOB="$ASSEMBLY/BlobTools"
export BLOBEXCLUDE="$BLOB/Exclude"
export FIXREADS="$ASSEMBLY/ReadsExtractor"
export PURGEDREADS="$FIXREADS/GCC14sorted.cleaned/"
export CONTAMREADS="$FIXREADS/GCC14sorted.contam/"

#############################
# ANNOTATION SUBDIRECTORIES #
#############################

export EVIDENCE="$ANNOTATION/Evidence"
export EDTA="$ANNOTATION/EDTA"
export REPEAT="$ANNOTATION/RepeatMasker"
export TRNA="$ANNOTATION/tRNAScan"
export INFERNAL="$ANNOTATION/Infernal"
export PYBAR="$ANNOTATION/PyBarrnap"
export GFF3="$ANNOTATION/GFF3Sanitizer"
export CLUSTER="$ANNOTATION/ClusterRemover"
export FUN2="$ANNOTATION/Funannotate2"
export GFACS="$ANNOTATION/gFACs"
export FIXER="$ANNOTATION/Fixer"
export ANTI="$ANNOTATION/antiSMASH"
export EGG="$ANNOTATION/eggNOG"
export IPR="$ANNOTATION/IPRScan"
export SIGNAL="$ANNOTATION/SignalP6"

############################
# PANGENOME SUBDIRECTORIES #
############################

export PANCLEAN="$PAN/PanClean"
export MASH="$PAN/MashTree"
export PARSE="$PAN/ParsedList"
export ORTHO="$PAN/Orthofinder"

#########################
# FUNCTIONAL MISCELLANY #
#########################

###if you want to use a different list of isolates from the one I used originally, replace this list with the isolate short name; do not use spaces inside of names, mind your capitalization, and single-space separate (not comma) the names; do not change the variable name, only its contents

export ISOLATES_ILL=(GCC05 GCC08 GS9 CSiam19 CSiam96 CSiam102 PS22 PS23 PS24 GCC14)
export ISOLATES_PB=(GCC05PB GCC14PB)
export ISOLATES=("${ISOLATES_ILL[@]}" "${ISOLATES_PB[@]}")

###if you intend to use a list of references different from what I have used, please replace the entries in the variable below with the specific Accession IDs you want to use as references; do not change the variable name, only its contents

export REFIDS=(GCA_018853505.1 GCA_026740055.1 GCA_011947485.2 GCF_013390195.1)
export TOPREFS=(Cg363 LS19)

###Choose one of your references to be the "Trainer" reference for annotation; it should be the highest quality reference and absolutely MUST have a genomic.gff file at NCBI; enter its strain ID in the variable below; it is case-sensitive! This is used for EDTA training only, and should be the reference with the best example repeat environment. You should use only a single reference per GENUS.

export TRAINER=Cg363

###While TRAINER is used for EDTA, TRAINING is used for ab initio gene prediction. You should use a separate reference per SPECIES.

export TRAINING=(Cg363 GCC14PB)

###once the above list has been populated, and the 0.ReferenceRetriever.sh script has been executed, the below variables will also work without further modification

if [[ -f "$REFS/references.txt" ]]; then
    REF_LIST=($(cat "$REFS/references.txt"))
    export ISOREFS=("${ISOLATES[@]}" "${REF_LIST[@]}")
else
    echo "WARNING: $REFS/references.txt not found. Please run 0.ReferenceRetriever.sh before any other scripts!"
    export ISOREFS=()
fi

###This array defines the species for each isolate entered; this is important during the annotation process for several tools to be able to identify how best to do their job based on the input species; every single isolate listed in the ISOLATES variable above, plus every single reference included in the STRAIN_LIST generated by references.txt must have an entry in this list or the code will fail

declare -A SPECIES_MAP

SPECIES_MAP=(
    [GCC05]="Colletotrichum siamense"
    [GCC05PB]="Colletotrichum siamense"
    [GCC08]="Colletotrichum siamense"
    [GS9]="Colletotrichum siamense"
    [Csiam19]="Colletotrichum siamense"
    [Csiam96]="Colletotrichum siamense"
    [Csiam102]="Colletotrichum siamense"
    [GCC14]="Colletotrichum camelliae"
    [GCC14PB]="Colletotrichum camelliae"
    [PS22]="Colletotrichum camelliae"
    [PS23]="Colletotrichum camelliae"
    [PS24]="Colletotrichum camelliae"
    [Cg363]="Colletotrichum siamense"
    [LS19]="Colletotrichum camelliae"
    [LT31]="Colletotrichum camelliae"
    [CcLH18]="Colletotrichum camelliae"
)